#!/usr/bin/env python3
"""
scripts/plotting/plot_red_box_frequency.py

Analyzes references generated by different models for mentions of 'red box', 'boxed object', etc.
Generates publication-quality bar chart with enlarged text.

Exports to gazeRL_publish/, figures/, workspace root, gazeRL/plots/, and artifact dir.
"""

import os
import glob
import re
import json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Configuration
EVAL_DIRS = [
    "/data/teaywright/gazerl_main_experiments/eval/",
    "/scratch/users/teaywright/gazerl_eval/",
    "/accounts/projects/berkeleynlp/teaywright/gazeRL_publish/results/eval_runs",
]

DATASETS = [
    "refcoco_testA",
    "refcoco_testB",
    "refoi_co_occurrence",
    "refoi_single_presence",
]

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": [
        "Palatino",
        "Palatino Linotype",
        "Palatino LT STD",
        "Book Antiqua",
        "Georgia",
        "DejaVu Serif",
        "serif",
    ],
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "axes.edgecolor": "#333333",
    "axes.linewidth": 1.0,
})

MODEL_MAP = {
    "gold_refs": "Human",
    "gold": "Human",
    "sparse_constant_kl_02": "Gaze-BFH",
    "shaping": "Gaze-Shaping",
    "iterative_sparse": "REC-BFH",
    "iterative_binary": "REC-SeqAnyHit",
    "supervised": "REC-Success",
    "binary_last_point": "Gaze-SeqLPHit",
    "binary": "Gaze-SeqAnyHit",
    "molmo_vanilla": "Molmo",
    "iterative_shaping": "REC-Shaping",
}

COLOR_MAP = {
    "Human": "#DAA520",
    "Gaze-BFH": "#22C55E",      # Vibrant emerald green
    "Gaze-Shaping": "#1B5E20",  # Dark forest green
    "REC-BFH": "brown",
    "REC-SeqAnyHit": "magenta",
    "REC-Success": "purple",
    "Gaze-SeqLPHit": "skyblue",
    "Gaze-SeqAnyHit": "navy",
    "Molmo": "black",
    "REC-Shaping": "red",
}

MODEL_ORDER = [
    "Molmo",
    "REC-BFH",
    "REC-Shaping",
    "REC-Success",
    "REC-SeqAnyHit",
    "Gaze-BFH",
    "Gaze-Shaping",
    "Gaze-SeqLPHit",
    "Gaze-SeqAnyHit",
    "Human",
]

# Keywords for "red box" mentions
RED_BOX_KEYWORDS = [
    r'red[-\s]?box',
    r'box(ed)?\s?object',
    r'boxed',
    r'redbox'
]


def mentions_red_box(text):
    if not isinstance(text, str):
        return False
    text = text.lower()
    for kw in RED_BOX_KEYWORDS:
        if re.search(kw, text):
            return True
    return False


def load_all_references():
    data = []
    processed_files = set()

    sorted_model_map = sorted(
        MODEL_MAP.items(), key=lambda x: len(x[0]), reverse=True
    )

    for eval_dir in EVAL_DIRS:
        if not os.path.exists(eval_dir):
            continue

        folders = [
            d
            for d in os.listdir(eval_dir)
            if os.path.isdir(os.path.join(eval_dir, d))
            and "refcoco_sft" not in d
        ]

        for folder in folders:
            model_name = "Other"
            for key, val in sorted_model_map:
                if key.lower() in folder.lower():
                    model_name = val
                    break

            if model_name == "Other":
                continue

            folder_path = os.path.join(eval_dir, folder)

            for dataset in DATASETS:
                pattern = f"{folder_path}/**/*{dataset}*.json"
                files = glob.glob(pattern, recursive=True)

                for file_path in files:
                    file_key = (model_name, dataset, os.path.basename(file_path))
                    if file_key in processed_files:
                        continue
                    processed_files.add(file_key)

                    try:
                        with open(file_path, "r") as f:
                            ref_json = json.load(f)

                            if isinstance(ref_json, dict):
                                ref_json = [ref_json]

                            for item in ref_json:
                                ref_text = item.get(
                                    "generated_reference",
                                    item.get(
                                        "reference",
                                        item.get("ref", item.get("text", "")),
                                    ),
                                )

                                if isinstance(ref_text, list) and ref_text:
                                    ref_text = ref_text[0]

                                data.append({
                                    "Model": model_name,
                                    "HasRedBox": 1 if mentions_red_box(ref_text) else 0
                                })
                    except Exception:
                        continue

    df = pd.DataFrame(data)
    if not df.empty:
        print("\nSuccessfully loaded reference counts per model:")
        print(df["Model"].value_counts())
    else:
        print("\nNo matching references found across directories.")

    return df


def main():
    print("Analyzing references for 'red box' mentions...")
    df = load_all_references()

    if df.empty:
        print("No data found to plot.")
        return

    # Calculate percentages per model
    stats = df.groupby('Model')['HasRedBox'].mean() * 100

    # Filter and sort models matching strategy plot
    actual_model_order = [m for m in MODEL_ORDER if m in stats.index]
    stats = stats.loc[actual_model_order]

    print("\n--- RED BOX MENTION PERCENTAGES ---")
    for m, v in stats.items():
        print(f"{m:20}: {v:.2f}%")

    # Plot with enlarged figure size and typography
    fig, ax = plt.subplots(figsize=(14, 7.5), dpi=300)

    bars = ax.bar(
        stats.index,
        stats.values,
        color=[COLOR_MAP.get(m, 'gray') for m in stats.index],
        edgecolor='black',
        linewidth=0.8,
        zorder=3
    )

    # Text labels on top of bars (enlarged)
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            height + 0.7,
            f'{height:.1f}%',
            ha='center',
            va='bottom',
            fontsize=15,
            fontweight='bold',
            zorder=4
        )

    # Larger typography matching user request
    ax.set_ylabel('Percentage of References (%)', fontsize=22, fontweight='bold', labelpad=12)
    ax.set_title('Frequency of "Red Box" / "Boxed Object" Mentions', fontsize=24, fontweight='bold', pad=22)

    ax.set_xticks(range(len(stats.index)))
    ax.set_xticklabels(stats.index, rotation=35, ha='right', fontsize=16, fontweight='bold')

    ax.tick_params(axis='y', labelsize=16)
    for label in ax.get_yticklabels():
        label.set_fontweight('bold')

    max_val = max(stats.values) if not stats.empty and max(stats.values) > 0 else 10
    ax.set_ylim(0, max_val * 1.15)
    ax.grid(axis='y', linestyle='--', alpha=0.4, zorder=0)

    plt.tight_layout()

    out_dirs = [
        Path("/accounts/projects/berkeleynlp/teaywright/gazeRL_publish"),
        Path("/accounts/projects/berkeleynlp/teaywright/gazeRL_publish/figures"),
        Path("/accounts/projects/berkeleynlp/teaywright"),
        Path("/accounts/projects/berkeleynlp/teaywright/gazeRL/plots"),
        Path("/accounts/projects/berkeleynlp/teaywright/.gemini/antigravity-cli/brain/4650fa71-f324-48ea-9c07-38c6865071e4"),
    ]

    for p in out_dirs:
        p.mkdir(exist_ok=True, parents=True)
        fig.savefig(p / "model_red_box_frequency.pdf", dpi=300, bbox_inches='tight')
        fig.savefig(p / "model_red_box_frequency.png", dpi=300, bbox_inches='tight')

    print("\n[SUCCESS] Saved model_red_box_frequency.pdf and model_red_box_frequency.png across target directories.")
    plt.close(fig)


if __name__ == "__main__":
    main()
